# Generated by Django 4.2.16 on 2024-10-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usergroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usergroup',
            table='usergroup',
        ),
    ]
