# Generated by Django 4.2 on 2024-10-09 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('renters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reservationDate', models.DateTimeField(auto_now_add=True)),
                ('pickupDate', models.DateField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('renters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renters.renters')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.AddConstraint(
            model_name='bookings',
            constraint=models.UniqueConstraint(fields=('renters', 'equipment'), name='unique_renter_equipment_booking'),
        ),
    ]
